# Generated by Django 3.2.13 on 2022-08-22 02:25

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension, BtreeGistExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('indexes_task_1', '0002_auto_20220808_1124'),
    ]

    operations = [
        BtreeGinExtension(),
        BtreeGistExtension(),
        TrigramExtension(),
        migrations.AlterIndexTogether(
            name='employee',
            index_together={('fname', 'iname', 'oname')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['fname', 'iname', 'oname'], name='name_index'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GistIndex(fields=['begin', 'end'], name='begin_end_index'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['country'], name='country_index'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['additional_info'], name='additional_info_gin_index'),
        ),
    ]
